### ISSUE TITLE
First disbursement should be 5% or (blockHeight%100)% ?

### ISSUE THREAD

**Issue by ashishawaghad** [GNSPS/solidity-golf-challenge-india#1]
Hi GNSPS,

Was just wondering if the initial value of X is redundant or the first disbursement should be a fixed 5%. Thanks.

**Comment by GNSPS** [comment]
`At deploy time X = 5 and after that X = <block height at last execution> % 100.` 😄 

As I said, if you can argue for your implementation based on my spec (but please read it correctly! 😄 ) I'll definitely accept it! 👍

**Comment by ashishawaghad** [comment]
Another one: `last execution` meaning execution of disburse function or 'any' function?

**Comment by GNSPS** [comment]
Again, I leave that to your judgment. But if you are unsure that means you can argue for your implementation and therefore you should go with whichever is best for the contest: either fewer characters or less gas.

**Comment by ashishawaghad** [comment]
Got it. Thanks.
